Update build and deploy

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -6,7 +6,7 @@ on:
       - 'main'
     paths-ignore:
       - '**/README.md'
-  workflow_dispatch:
+#  workflow_dispatch:
 
 env:
   ACTIONS_STEP_DEBUG: true
@@ -29,36 +29,36 @@ jobs:
       - name: Initialize Sub-Packages
         run: npm run init-project container
 
-      - name: Initialize project agin
+      - name: Initialize Project
         run: npm run init-project twice
 
       - name: build tapis-ui
         run: npm run build
-#        run: |
-#          echo "Initializing TapisUI sub-packages..."
-#          # Directories to build
-#          dirs=(
-#            "packages/tapisui-api"
-#            "packages/tapisui-hooks"
-#            "packages/tapisui-common"
-#            "packages/tapisui-extensions-core"
-#            "packages/tapisui-extension-devtools"
-#            "packages/icicle-tapisui-extension"
-#            ""
-#          )
-#
-#          for dir in "${dirs[@]}"; do
-#            echo "Processing $dir..."
-#            cd "$dir" || { echo "Package directory $dir does not exist"; exit 1; }
-#            echo "Installing dependencies..."
-#            npm install --verbose || { echo "Failed to install dependencies in $dir"; exit 1; }
-#            echo "Building package..."
-#            npm run build || { echo "Failed to build package in $dir"; exit 1; }
-#            cd ../../ || exit 1
-#          done
+      #        run: |
+      #          echo "Initializing TapisUI sub-packages..."
+      #          # Directories to build
+      #          dirs=(
+      #            "packages/tapisui-api"
+      #            "packages/tapisui-hooks"
+      #            "packages/tapisui-common"
+      #            "packages/tapisui-extensions-core"
+      #            "packages/tapisui-extension-devtools"
+      #            "packages/icicle-tapisui-extension"
+      #            ""
+      #          )
+      #
+      #          for dir in "${dirs[@]}"; do
+      #            echo "Processing $dir..."
+      #            cd "$dir" || { echo "Package directory $dir does not exist"; exit 1; }
+      #            echo "Installing dependencies..."
+      #            npm install --verbose || { echo "Failed to install dependencies in $dir"; exit 1; }
+      #            echo "Building package..."
+      #            npm run build || { echo "Failed to build package in $dir"; exit 1; }
+      #            cd ../../ || exit 1
+      #          done
 
-#      - name: Format Code
-#        run: npm run prettier
+      #      - name: Format Code
+      #        run: npm run prettier
 
       # - name: add config
       #   run: echo "${{ secrets.CONFIG_JSON }}" | base64 -d > src/config.json
